Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "bento/centos-6.9"
  c.vm.hostname = "Nagios-centos-69.vagrantup.com"
  c.vm.network(:private_network, {:ip=>"192.168.56.108"})
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "/root/.kitchen/cache", "/tmp/omnibus/cache", create: true
  c.vm.provider :virtualbox do |p|
    p.customize ["modifyvm", :id, "--memory", "1024"]
    p.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
  end
end
