---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.9

suites:
  # Nagios Server
  - name: Nagios
    data_bags_path: "test/integration/data_bags" 
    run_list:
      - recipe[nagios-cookbook::default]
    attributes:
    driver:
        network:
            - ["private_network", {ip: "192.168.56.108"}]
        customize: 
            memory: 1024 
            cpuexecutioncap: 50




